# Generated by Django 6.0.2 on 2026-02-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('score', models.FloatField(help_text='Score based on indicator measurement type')),
                ('assessment_type', models.CharField(choices=[('baseline', 'Baseline'), ('progress', 'Progress Check'), ('midterm', 'Midterm'), ('final', 'Final')], default='progress', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic Skills'), ('social', 'Social-Emotional Development'), ('physical', 'Physical Development'), ('vocational', 'Vocational Skills'), ('life_skills', 'Life Skills'), ('other', 'Other')], max_length=50)),
                ('measurement_type', models.CharField(choices=[('scale_1_10', 'Scale (1-10)'), ('scale_1_5', 'Scale (1-5)'), ('percentage', 'Percentage (0-100)'), ('binary', 'Pass/Fail'), ('score', 'Raw Score')], max_length=20)),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=10)),
                ('interpretation_guide', models.TextField(blank=True, help_text='Guidelines for interpreting scores')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'db_table': 'indicators',
                'ordering': ['category', 'name'],
            },
        ),
    ]
