# Generated by Django 6.0.2 on 2026-02-07 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('participants', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='participants.participant'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='programs.program'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.indicator'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['participant', 'indicator'], name='assessments_partici_048f46_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['program', 'indicator'], name='assessments_program_fd953c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_date'], name='assessments_assessm_4c5298_idx'),
        ),
    ]
