# Generated by Django 6.0.2 on 2026-02-07 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'program_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmilestone',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='programs.program'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['location', 'status'], name='programs_locatio_b71d94_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['start_date', 'end_date'], name='programs_start_d_976bd0_idx'),
        ),
    ]
