# Generated by Django 6.0.2 on 2026-02-07 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('excused_absence', 'Excused Absence'), ('medical', 'Medical Reason'), ('family_emergency', 'Family Emergency'), ('official_business', 'Official Business'), ('late_justified', 'Justified Late Arrival'), ('early_justified', 'Justified Early Departure'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField(help_text='Detailed reason for exception')),
                ('documentation_provided', models.BooleanField(default=False, help_text='Whether supporting documentation was provided')),
                ('documentation_file', models.FileField(blank=True, help_text='Upload supporting documentation (e.g., medical note)', null=True, upload_to='attendance/exceptions/%Y/%m/')),
                ('approved', models.BooleanField(default=False, help_text='Whether exception was approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Exception',
                'verbose_name_plural': 'Attendance Exceptions',
                'db_table': 'attendance_exceptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_name', models.CharField(blank=True, help_text="Optional session identifier (e.g., 'Morning Session', 'Workshop A')", max_length=200)),
                ('present', models.BooleanField(default=False)),
                ('verification_method', models.CharField(choices=[('manual', 'Manual Entry'), ('face_recognition', 'Face Recognition'), ('qr_code', 'QR Code Scan'), ('signature', 'Signature'), ('other', 'Other')], default='manual', max_length=20)),
                ('verified_by_face', models.BooleanField(default=False, help_text='Whether attendance was verified using face recognition')),
                ('confidence_score', models.FloatField(blank=True, help_text='Face recognition confidence score (0-1, higher = more confident)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('face_distance', models.FloatField(blank=True, help_text='Face matching distance (0-1, lower = better match)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('face_image', models.ImageField(blank=True, help_text='Captured face image for verification (optional)', null=True, upload_to='attendance/faces/%Y/%m/%d/')),
                ('arrival_time', models.TimeField(blank=True, help_text='Time participant arrived', null=True)),
                ('departure_time', models.TimeField(blank=True, help_text='Time participant left', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('late_arrival', models.BooleanField(default=False, help_text='Mark if participant arrived late')),
                ('early_departure', models.BooleanField(default=False, help_text='Mark if participant left early')),
                ('excused_absence', models.BooleanField(default=False, help_text='Mark if absence was excused')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_records',
                'ordering': ['-date', 'program', 'participant'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text="Session identifier (e.g., 'Morning Session', 'Workshop 1')", max_length=200)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, help_text='Specific location within program site', max_length=200)),
                ('room', models.CharField(blank=True, help_text='Room number or name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Session description or agenda')),
                ('session_type', models.CharField(blank=True, choices=[('class', 'Class/Lecture'), ('workshop', 'Workshop'), ('activity', 'Activity'), ('assessment', 'Assessment'), ('field_trip', 'Field Trip'), ('other', 'Other')], help_text='Type of session', max_length=50)),
                ('max_capacity', models.IntegerField(blank=True, help_text='Maximum number of participants', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_completed', models.BooleanField(default=False, help_text='Mark when session has ended')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Mark if session was cancelled')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('require_face_verification', models.BooleanField(default=False, help_text='Require face recognition for this session')),
                ('allow_manual_override', models.BooleanField(default=True, help_text='Allow manual attendance entry if face recognition fails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'db_table': 'attendance_sessions',
                'ordering': ['-session_date', 'start_time'],
            },
        ),
    ]
