# Generated by Django 6.0.2 on 2026-02-07 07:31

import django.core.validators
import participants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped Out'), ('transferred', 'Transferred')], default='enrolled', max_length=20)),
                ('attendance_rate', models.FloatField(default=0.0, help_text='Percentage of sessions attended', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('exit_reason', models.TextField(blank=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=participants.models.generate_participant_id, editable=False, help_text='Auto-generated unique identifier (e.g., YP-2024-A3B9C2)', max_length=50, unique=True)),
                ('age', models.IntegerField(help_text='Age at enrollment', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('photo', models.ImageField(blank=True, help_text='Photo for face recognition attendance (requires guardian consent)', null=True, upload_to='participants/photos/')),
                ('face_encoding', models.JSONField(blank=True, help_text='Stored face encoding for recognition (auto-generated from photo)', null=True)),
                ('face_encoding_date', models.DateTimeField(blank=True, help_text='When the face encoding was last updated', null=True)),
                ('photo_consent_given', models.BooleanField(default=False, help_text='Guardian consent for photo storage and face recognition')),
                ('data_sharing_consent', models.BooleanField(default=False, help_text='Consent for sharing anonymized data with donors')),
                ('education_level', models.CharField(blank=True, choices=[('none', 'No Formal Education'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('vocational', 'Vocational Training'), ('university', 'University')], max_length=50)),
                ('special_needs', models.TextField(blank=True, help_text='Any special needs or accommodations required')),
                ('enrollment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': 'participants',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField()),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('concern', 'Concern'), ('achievement', 'Achievement'), ('behavior', 'Behavioral Observation'), ('other', 'Other')], default='progress', max_length=20)),
                ('content', models.TextField()),
                ('is_confidential', models.BooleanField(default=False, help_text='Visible only to authorized staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'participant_notes',
                'ordering': ['-note_date', '-created_at'],
            },
        ),
    ]
