# Generated by Django 6.0.2 on 2026-02-07 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.program'),
        ),
        migrations.AddField(
            model_name='participant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='participants.participant'),
        ),
        migrations.AddField(
            model_name='participantnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantnote',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_notes', to='participants.enrollment'),
        ),
        migrations.AddField(
            model_name='participantnote',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='participants.participant'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['participant_id'], name='participant_partici_a79cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['enrollment_date'], name='participant_enrollm_9d2722_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_active'], name='participant_is_acti_48d6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['participant', 'status'], name='enrollments_partici_2f1af7_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['program', 'status'], name='enrollments_program_973e56_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_date'], name='enrollments_enrollm_4c2d2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('participant', 'program')},
        ),
    ]
