# Generated by Django 6.0.2 on 2026-02-11 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default=1, help_text="Participant's first name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default=1, help_text="Participant's last name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['first_name', 'last_name'], name='participant_first_n_08b4f7_idx'),
        ),
    ]
