# Generated by Django 6.0.2 on 2026-03-01 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participant_first_name_participant_last_name_and_more'),
        ('programs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Room name or identifier (e.g., 'Room A', 'Blue Class')", max_length=200)),
                ('capacity', models.IntegerField(default=30, help_text='Maximum number of participants in this room', validators=[django.core.validators.MinValueValidator(1)])),
                ('schedule', models.TextField(blank=True, help_text="Class schedule (e.g., 'Mon-Fri 9AM-12PM')")),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['program', 'name'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='dropout_date',
            field=models.DateField(blank=True, help_text='Date participant dropped out', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='dropout_notes',
            field=models.TextField(blank=True, help_text='Additional notes about dropout'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='dropout_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Successfully Completed Program'), ('dropout_personal', 'Dropout - Personal Reasons'), ('dropout_financial', 'Dropout - Financial Difficulties'), ('dropout_relocation', 'Dropout - Family Relocation'), ('dropout_health', 'Dropout - Health Issues'), ('dropout_behavior', 'Dropout - Behavioral Issues'), ('transferred', 'Transferred to Another Program'), ('scholarship', 'Received Scholarship for Further Education'), ('other', 'Other')], help_text='Reason for dropout', max_length=50),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_grade',
            field=models.CharField(blank=True, choices=[('A', 'Excellent (A)'), ('B', 'Very Good (B)'), ('C', 'Good (C)'), ('D', 'Pass (D)'), ('F', 'Fail (F)')], help_text='Final assessment grade', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='finish_date',
            field=models.DateField(blank=True, help_text='Date participant completed the program', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='has_dropped_out',
            field=models.BooleanField(default=False, help_text='Whether participant dropped out'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='has_finished',
            field=models.BooleanField(default=False, help_text='Whether participant successfully finished the program'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='has_scholarship',
            field=models.BooleanField(default=False, help_text='Whether participant received a scholarship'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='scholarship_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Scholarship amount in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='scholarship_date',
            field=models.DateField(blank=True, help_text='Date scholarship was awarded', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='scholarship_notes',
            field=models.TextField(blank=True, help_text='Additional scholarship details'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='scholarship_provider',
            field=models.CharField(blank=True, help_text='Organization or individual providing scholarship', max_length=200),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='scholarship_type',
            field=models.CharField(blank=True, choices=[('full', 'Full Scholarship'), ('partial', 'Partial Scholarship'), ('merit', 'Merit-Based Scholarship'), ('need', 'Need-Based Scholarship'), ('vocational', 'Vocational Training Scholarship'), ('university', 'University Scholarship'), ('other', 'Other Scholarship')], help_text='Type of scholarship awarded', max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped Out'), ('transferred', 'Transferred'), ('scholarship', 'Scholarship Awarded')], default='enrolled', max_length=20),
        ),
        migrations.AlterField(
            model_name='participantnote',
            name='note_type',
            field=models.CharField(choices=[('progress', 'Progress Note'), ('concern', 'Concern'), ('achievement', 'Achievement'), ('behavior', 'Behavioral Observation'), ('scholarship', 'Scholarship Related'), ('other', 'Other')], default='progress', max_length=20),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['has_finished'], name='enrollments_has_fin_bbf0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['has_dropped_out'], name='enrollments_has_dro_76eb90_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['has_scholarship'], name='enrollments_has_sch_675e1c_idx'),
        ),
        migrations.AddField(
            model_name='room',
            name='program',
            field=models.ForeignKey(help_text='Program this room belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='programs.program'),
        ),
        migrations.AddField(
            model_name='room',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher/facilitator assigned to this room', limit_choices_to={'role__in': ['admin', 'program_manager', 'data_entry']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room/classroom this participant is assigned to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='participants.room'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room'], name='participant_room_id_8169ee_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['program', 'is_active'], name='rooms_program_e74728_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['teacher'], name='rooms_teacher_727b3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('program', 'name')},
        ),
    ]
