# Generated by Django 6.0.2 on 2026-04-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('courses', models.CharField(max_length=500)),
                ('parent_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('dropped_out', 'Dropped Out')], default='active', max_length=20)),
                ('midterm_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_out_at', models.DateTimeField(blank=True, null=True)),
                ('dropout_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
