# Generated by Django 6.0.2 on 2026-02-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='reports/%Y/%m/')),
                ('parameters', models.JSONField(help_text='Report filters and parameters')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
            ],
            options={
                'db_table': 'generated_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('donor_quarterly', 'Donor Quarterly Report'), ('program_summary', 'Program Summary'), ('impact_assessment', 'Impact Assessment'), ('participant_progress', 'Participant Progress Report'), ('attendance_report', 'Attendance Report')], max_length=30)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
